# Generated by Django 3.2.4 on 2023-11-14 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='perfil',
            table='perfil',
        ),
    ]
