# Generated by Django 3.2.4 on 2023-11-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20231114_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='tipos_proyectos',
            new_name='challenge_devs',
        ),
        migrations.AddField(
            model_name='perfil',
            name='frame_works',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='online_community',
            field=models.TextField(blank=True, null=True),
        ),
    ]
