# Generated by Django 3.2.4 on 2023-11-22 02:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20231121_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fecha_realizacion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
