# Generated by Django 3.2.4 on 2023-11-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_perfil_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='validacion',
            field=models.BooleanField(default=True),
        ),
    ]
