# Generated by Django 3.2.4 on 2023-11-25 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_validar'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='validar',
            table='validar',
        ),
    ]
