# Generated by Django 3.2.4 on 2023-11-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_validar_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='validacion',
        ),
        migrations.AddField(
            model_name='perfil',
            name='curriculum_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
